{
 "title": "AWS Aurora MySQL Metrics 2",
 "description": "更新时间2021-03-11",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "dbcluster_identifier", "label": "DB-Cluster", "query": " " },
   { "name": "role", "label": "Role", "query": "READER,WRITER" },
   { "name": "rds", "label": "RDS", "query": "1" }
  ]
 },
 "panels": [
  {
   "title": "Aurora MySQL Role",
   "type": "singlestat",
   "description": "集群实例角色\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_innodb_read_only "
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "singlestat",
   "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries[$interval]) or irate(mysql_global_status_queries[5m])"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Size",
   "type": "singlestat",
   "description": "**InnoDB Buffer Pool Size**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_innodb_buffer_pool_size"
    }
   ]
  },
  {
   "title": "MySQL Uptime",
   "type": "singlestat",
   "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "calculatedInterval": "10m", "expr": "mysql_global_status_uptime" }
   ]
  },
  {
   "title": "Aurora MySQL Version",
   "type": "table",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "targets": [
    { "expr": "mysql_version_info" }
   ]
  },
  {
   "title": "Current TPS",
   "type": "singlestat",
   "description": "**Current TPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_auroradb_commits[$interval]) or irate(mysql_global_status_auroradb_commits[5m])"
    }
   ]
  },
  {
   "title": "活跃连接数",
   "type": "singlestat",
   "description": "**Threads Connected**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_threads_connected "
    }
   ]
  },
  {
   "title": "Aurora MySQL Freeable Memory",
   "type": "bargauge",
   "description": "Aurora 数据库实例随机存取内存的可用大小。",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aws_rds_freeable_memory_average"
    }
   ]
  },
  {
   "title": "Amazon MySQL Metrics Guide",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
     "options": {
      "content": "# Amazon Aurora Metrics\n\n> This is a Demo for DBA Team, Plz Don't Drop it.\n* Prometheus MySQL Exporter\n* AWS Aurora Performance baseline\n* AWS Aurora Enhanced Monitoring\n* AWS Aurora Performance Insights"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 10 },
     "options": {
      "content": "##### Prometheus MySQL Exporter For AWS Aurora\n\n| No.  | Desc                                                         |\n| ---- | ------------------------------------------------------------ |\n| 1    | [指标明细列表（UP & Version）](https://docs.google.com/spreadsheets/d/1Dze23GhqQ2a_YK6EgwNXyA7EX5GhXWOQPy9V_yl9yxk/edit#gid=0) |\n| 2    | [指标明细列表（Global Variables）](https://docs.google.com/spreadsheets/d/1Dze23GhqQ2a_YK6EgwNXyA7EX5GhXWOQPy9V_yl9yxk/edit#gid=1886340298) |\n| 3    | [指标明细列表（Global Status）](https://docs.google.com/spreadsheets/d/1Dze23GhqQ2a_YK6EgwNXyA7EX5GhXWOQPy9V_yl9yxk/edit#gid=278622012) |\n| 4    | [指标明细列表（InnoDB Metrics）](https://docs.google.com/spreadsheets/d/1Dze23GhqQ2a_YK6EgwNXyA7EX5GhXWOQPy9V_yl9yxk/edit#gid=1971096351) |\n| 5    | [指标明细列表（Processes）](https://docs.google.com/spreadsheets/d/1Dze23GhqQ2a_YK6EgwNXyA7EX5GhXWOQPy9V_yl9yxk/edit#gid=114522435) |\n| 6    | [指标明细列表（Threads）](https://docs.google.com/spreadsheets/d/1Dze23GhqQ2a_YK6EgwNXyA7EX5GhXWOQPy9V_yl9yxk/edit#gid=1819875275) |\n| 7    | [指标明细列表（Table）](https://docs.google.com/spreadsheets/d/1Dze23GhqQ2a_YK6EgwNXyA7EX5GhXWOQPy9V_yl9yxk/edit#gid=1856937499) |\n| 8    | [指标明细列表（Auto Increment）](https://docs.google.com/spreadsheets/d/1Dze23GhqQ2a_YK6EgwNXyA7EX5GhXWOQPy9V_yl9yxk/edit#gid=1868610922) |\n| 9    | [指标明细列表（Binlog Files）](https://docs.google.com/spreadsheets/d/1Dze23GhqQ2a_YK6EgwNXyA7EX5GhXWOQPy9V_yl9yxk/edit#gid=2132172184) |"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 10 },
     "options": {
      "content": "##### AWS Aurora Performance baseline\n\n| No.  | Desc                                                         |\n| ---- | ------------------------------------------------------------ |\n| 1                               | [Amazon Aurora 的集群级指标](https://docs.google.com/spreadsheets/d/1Dze23GhqQ2a_YK6EgwNXyA7EX5GhXWOQPy9V_yl9yxk/edit#gid=291780899)        |\n| 2                               | [Amazon Aurora 的实例级指标](https://docs.google.com/spreadsheets/d/1Dze23GhqQ2a_YK6EgwNXyA7EX5GhXWOQPy9V_yl9yxk/edit#gid=1202602339)       |\n\n##### AWS Aurora Enhanced Monitoring\n\n| No.  | Desc                                                         |\n| ---- | ------------------------------------------------------------ |\n| 1                               | [AWS Aurora Enhanced Monitoring](https://docs.google.com/spreadsheets/d/1Dze23GhqQ2a_YK6EgwNXyA7EX5GhXWOQPy9V_yl9yxk/edit#gid=157863871)    |\n\n##### AWS Aurora Performance Insights\n| No.  | Desc                                                         |\n| ---- | ------------------------------------------------------------ |\n| 1                               | [AWS Aurora Performance Insights](https://docs.google.com/spreadsheets/d/1Dze23GhqQ2a_YK6EgwNXyA7EX5GhXWOQPy9V_yl9yxk/edit#gid=2137510754)  |"
     }
    }
   ]
  },
  { "title": "Trx & Binlog Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Binlog Size [ 1m ] 变化趋势",
   "type": "graph",
   "description": "1分钟内 binlog files 大小变化趋势",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mysql_binlog_size_bytes  - mysql_binlog_size_bytes offset 1m",
     "legendFormat": "binlog size"
    }
   ]
  },
  {
   "title": "Transaction Trx Rseg History Len",
   "type": "graph",
   "description": "Length of the TRX_RSEG_HISTORY list\n当写库并发执行大查询的时候，transaction history就会因为undo log无法purge而一直增加。",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_info_schema_innodb_metrics_transaction_trx_rseg_history_len",
     "legendFormat": "TRX_RSEG_HISTORY"
    }
   ]
  },
  {
   "title": "Binlog Size [ 1m ] 变化趋势",
   "type": "heatmap",
   "description": "1分钟内 binlog files 大小变化趋势",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "mysql_binlog_size_bytes offset 1m - mysql_binlog_size_bytes  > 0",
     "legendFormat": "binlog size"
    }
   ]
  },
  {
   "title": "The last binlog file number.",
   "type": "stat",
   "description": "mysql_binlog_file_number",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_binlog_file_number", "legendFormat": "The last binlog file number." }
   ]
  },
  {
   "title": "Combined size of all registered binlog files.",
   "type": "stat",
   "description": "mysql_binlog_size_bytes",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_binlog_size_bytes",
     "legendFormat": "Combined size of all registered binlog files."
    }
   ]
  },
  {
   "title": "Number of registered binlog files.",
   "type": "stat",
   "description": "mysql_binlog_files",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_binlog_files",
     "legendFormat": "Number of registered binlog files."
    }
   ]
  },
  {
   "title": "1 Prometheus MySQL Exporter For AWS Aurora",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  { "title": "1.1 Connections & Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "MySQL Connections",
   "type": "graph",
   "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max(max_over_time(mysql_global_status_threads_connected[$interval])  or mysql_global_status_threads_connected )",
     "legendFormat": "Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_max_used_connections",
     "legendFormat": "Max Used Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections",
     "legendFormat": "Max Connections"
    }
   ]
  },
  {
   "title": "MySQL Client Thread Activity",
   "type": "graph",
   "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_threads_connected[$interval]) or\nmax_over_time(mysql_global_status_threads_connected[5m])",
     "legendFormat": "Peak Threads Connected"
    },
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_threads_running[$interval]) or\nmax_over_time(mysql_global_status_threads_running[5m])",
     "legendFormat": "Peak Threads Running"
    },
    {
     "expr": "avg_over_time(mysql_global_status_threads_running[$interval]) or \navg_over_time(mysql_global_status_threads_running[5m])",
     "legendFormat": "Avg Threads Running"
    }
   ]
  },
  {
   "title": "MySQL Processes By User",
   "type": "graph",
   "description": "select count(*) from processes group by user \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_processes_by_user",
     "legendFormat": " {{mysql_user}}"
    }
   ]
  },
  {
   "title": "MySQL Processes By Host",
   "type": "graph",
   "description": "select count(*) from processes group by host \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_processes_by_host",
     "legendFormat": "{{client_host}}"
    }
   ]
  },
  {
   "title": "MySQL Connection Errors",
   "type": "bargauge",
   "description": "由服务器错误导致的失败连接次数\n\nWhen a given host connects to MySQL and the connection is interrupted in the middle (for example due to bad credentials), MySQL keeps that info in a system table (since 5.6 this table is exposed in performance_schema).\n\nIf the amount of failed requests without a successful connection reaches the value of max_connect_errors, mysqld assumes that something is wrong and blocks the host from further connection.\n\nTo allow connections from that host again, you need to issue the ``FLUSH HOSTS`` statement.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_connection_errors_total[$interval]) or irate(mysql_global_status_connection_errors_total[5m])",
     "legendFormat": "Error - {{error}}"
    }
   ]
  },
  {
   "title": "MySQL Aborted Connections",
   "type": "graph",
   "description": "**Aborted Connections**\n\nWhen a given host connects to MySQL and the connection is interrupted in the middle (for example due to bad credentials), MySQL keeps that info in a system table (since 5.6 this table is exposed in performance_schema).\n\nIf the amount of failed requests without a successful connection reaches the value of max_connect_errors, mysqld assumes that something is wrong and blocks the host from further connection.\n\nTo allow connections from that host again, you need to issue the ``FLUSH HOSTS`` statement.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aborted_connects[$interval]) or irate(mysql_global_status_aborted_connects[5m])",
     "legendFormat": "Aborted Connects (attempts)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aborted_clients[$interval]) or irate(mysql_global_status_aborted_clients[5m])",
     "legendFormat": "Aborted Clients (timeout)"
    }
   ]
  },
  {
   "title": "MySQL Thread Cache",
   "type": "graph",
   "description": "**MySQL Thread Cache**\n\nThe thread_cache_size variable sets how many threads the server should cache to reuse. When a client disconnects, the client's threads are put in the cache if the cache is not full. It is autosized in MySQL 5.6.8 and above (capped to 100). Requests for threads are satisfied by reusing threads taken from the cache if possible, and only when the cache is empty is a new thread created.\n\n* *Threads_created*: The number of threads created to handle connections.\n* *Threads_cached*: The number of threads in the thread cache.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_thread_cache_size",
     "legendFormat": "Thread Cache Size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_threads_cached",
     "legendFormat": "Threads Cached"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_threads_created[$interval]) or irate(mysql_global_status_threads_created[5m])",
     "legendFormat": "Threads Created"
    }
   ]
  },
  {
   "title": "Process States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "calculatedInterval": "2m", "expr": "mysql_info_schema_threads", "legendFormat": "{{ state }}" }
   ]
  },
  {
   "title": "Top Process States Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, avg_over_time(mysql_info_schema_threads[1h]))",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "1.2 Table & Column", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "MySQL Table Rows",
   "type": "table",
   "description": "Table size\n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_table_size{container_name=~\"$rds\",schema != \"sys\", component=\"data_length\"}",
     "legendFormat": "Table Size - {{schema}}.{{table}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_table_size{container_name=~\"$rds\",schema != \"sys\",component=\"index_length\"}",
     "legendFormat": "Table Size - {{schema}}.{{table}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_table_size{container_name=~\"$rds\",schema != \"sys\", component=\"data_free\"}",
     "legendFormat": "Table Size - {{schema}}.{{table}}"
    }
   ]
  },
  {
   "title": "MySQL Table Rows",
   "type": "table",
   "description": "Table size\n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_table_size{container_name=~\"$rds\",schema != \"sys\", component=\"data_length\"}",
     "legendFormat": "Table Size - {{schema}}.{{table}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_table_size{container_name=~\"$rds\",schema != \"sys\",component=\"index_length\"}",
     "legendFormat": "Table Size - {{schema}}.{{table}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_table_size{container_name=~\"$rds\",schema != \"sys\", component=\"data_free\"}",
     "legendFormat": "Table Size - {{schema}}.{{table}}"
    }
   ]
  },
  {
   "title": "MySQL Auto Increment Column",
   "type": "graph",
   "description": "**Max Auto Increment Column** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_auto_increment_column",
     "legendFormat": "Used Auto Increment Column - {{schema}}.{{table}} - {{column}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_auto_increment_column_max",
     "legendFormat": "Max Auto Increment Column - {{schema}}.{{table}} - {{column}}"
    }
   ]
  },
  {
   "title": "MySQL Auto Increment Column",
   "type": "table",
   "description": "**Max Auto Increment Column** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_auto_increment_column",
     "legendFormat": "Used Auto Increment Column - {{schema}}.{{table}} - {{column}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_auto_increment_column_max",
     "legendFormat": "Max Auto Increment Column - {{schema}}.{{table}} - {{column}}"
    }
   ]
  },
  { "title": "1.3 Buffer & Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "InnoDB Buffer Pool 请求",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_buffer_pool_read_requests[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_requests[5m])",
     "legendFormat": "InnoDB Buffer Pool 每秒读次数"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_buffer_pool_write_requests[$interval]) or irate(mysql_global_status_innodb_buffer_pool_write_requests[5m])",
     "legendFormat": "InnoDB Buffer Pool 每秒写次数"
    }
   ]
  },
  {
   "title": "InnoDB 缓存命中率",
   "type": "gauge",
   "description": "（Innodb_buffer_pool_read_requests - Innodb_buffer_pool_reads） / Innodb_buffer_pool_read_requests * 100%\n一般来讲这个命中率不会低于99%，如果低于这个值的话就要考虑加大innodb buffer pool。",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_buffer_pool_reads",
     "legendFormat": "读取数据的请求次数（物理磁盘）"
    },
    {
     "expr": "mysql_global_status_innodb_buffer_pool_read_requests",
     "legendFormat": "读取数据的请求次数（总数）"
    }
   ]
  },
  {
   "title": "MySQL Internal Memory Overview",
   "type": "graph",
   "description": "***System Memory***: Total Memory for the system.\\\n***InnoDB Buffer Pool Data***: InnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.\\\n***TokuDB Cache Size***: Similar in function to the InnoDB Buffer Pool,  TokuDB will allocate 50% of the installed RAM for its own cache.\\\n***Key Buffer Size***: Index blocks for MYISAM tables are buffered and are shared by all threads. key_buffer_size is the size of the buffer used for index blocks.\\\n***Adaptive Hash Index Size***: When InnoDB notices that some index values are being accessed very frequently, it builds a hash index for them in memory on top of B-Tree indexes.\\\n ***Query Cache Size***: The query cache stores the text of a SELECT statement together with the corresponding result that was sent to the client. The query cache has huge scalability problems in that only one thread can do an operation in the query cache at the same time.\\\n***InnoDB Dictionary Size***: The data dictionary is InnoDB ‘s internal catalog of tables. InnoDB stores the data dictionary on disk, and loads entries into memory while the server is running.\\\n***InnoDB Log Buffer Size***: The MySQL InnoDB log buffer allows transactions to run without having to write the log to disk before the transactions commit.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal", "legendFormat": "System Memory" },
    {
     "expr": "mysql_global_status_innodb_page_size * on (instance) mysql_global_status_buffer_pool_pages{container_name=~\"$rds\",state=\"data\"}",
     "legendFormat": "InnoDB Buffer Pool Data"
    },
    {
     "expr": "mysql_global_variables_innodb_log_buffer_size",
     "legendFormat": "InnoDB Log Buffer Size"
    },
    {
     "expr": "mysql_global_variables_innodb_additional_mem_pool_size",
     "legendFormat": "InnoDB Additional Memory Pool Size"
    },
    {
     "expr": "mysql_global_status_innodb_mem_dictionary",
     "legendFormat": "InnoDB Dictionary Size"
    },
    {
     "expr": "mysql_global_variables_key_buffer_size",
     "legendFormat": "Key Buffer Size"
    },
    {
     "expr": "mysql_global_variables_query_cache_size",
     "legendFormat": "Query Cache Size"
    },
    {
     "expr": "mysql_global_status_innodb_mem_adaptive_hash",
     "legendFormat": "Adaptive Hash Index Size"
    },
    {
     "expr": "mysql_global_variables_tokudb_cache_size",
     "legendFormat": "TokuDB Cache Size"
    }
   ]
  },
  {
   "title": "MySQL Table Definition Cache",
   "type": "graph",
   "description": "**MySQL Table Definition Cache**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_table_definitions",
     "legendFormat": "Open Table Definitions"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_definition_cache",
     "legendFormat": "Table Definitions Cache Size"
    },
    {
     "expr": "rate(mysql_global_status_opened_table_definitions[$interval]) or irate(mysql_global_status_opened_table_definitions[5m])",
     "legendFormat": "Opened Table Definitions"
    }
   ]
  },
  {
   "title": "MySQL Query Cache Memory",
   "type": "graph",
   "description": "**MySQL Query Cache Memory**\n\nThe query cache has huge scalability problems in that only one thread can do an operation in the query cache at the same time. This serialization is true not only for SELECTs, but also for INSERT/UPDATE/DELETE.\n\nThis also means that the larger the `query_cache_size` is set to, the slower those operations become. In concurrent environments, the MySQL Query Cache quickly becomes a contention point, decreasing performance. MariaDB and AWS Aurora have done work to try and eliminate the query cache contention in their flavors of MySQL, while MySQL 8.0 has eliminated the query cache feature.\n\nThe recommended settings for most environments is to set:\n  ``query_cache_type=0``\n  ``query_cache_size=0``\n\nNote that while you can dynamically change these values, to completely remove the contention point you have to restart the database.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_qcache_free_memory",
     "legendFormat": "Free Memory"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_query_cache_size",
     "legendFormat": "Query Cache Size"
    }
   ]
  },
  {
   "title": "MySQL Query Cache Activity",
   "type": "graph",
   "description": "**MySQL Query Cache Activity**\n\nThe query cache has huge scalability problems in that only one thread can do an operation in the query cache at the same time. This serialization is true not only for SELECTs, but also for INSERT/UPDATE/DELETE.\n\nThis also means that the larger the `query_cache_size` is set to, the slower those operations become. In concurrent environments, the MySQL Query Cache quickly becomes a contention point, decreasing performance. MariaDB and AWS Aurora have done work to try and eliminate the query cache contention in their flavors of MySQL, while MySQL 8.0 has eliminated the query cache feature.\n\nThe recommended settings for most environments is to set:\n``query_cache_type=0``\n``query_cache_size=0``\n\nNote that while you can dynamically change these values, to completely remove the contention point you have to restart the database.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_qcache_hits[$interval]) or irate(mysql_global_status_qcache_hits[5m])",
     "legendFormat": "Hits"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_qcache_inserts[$interval]) or irate(mysql_global_status_qcache_inserts[5m])",
     "legendFormat": "Inserts"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_qcache_not_cached[$interval]) or irate(mysql_global_status_qcache_not_cached[5m])",
     "legendFormat": "Not Cached"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_qcache_lowmem_prunes[$interval]) or irate(mysql_global_status_qcache_lowmem_prunes[5m])",
     "legendFormat": "Prunes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_qcache_queries_in_cache",
     "legendFormat": "Queries in Cache"
    }
   ]
  },
  { "title": "1.4 Query Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "MySQL QPS",
   "type": "graph",
   "description": "平均每秒SQL语句执行的次数\n\nThe number of statements executed by the server. This includes only statements sent to the server by clients and not statements executed within stored programs, unlike the Queries used in the QPS calculation. \n\nThis variable does not count the following commands:\n* ``COM_PING``\n* ``COM_STATISTICS``\n* ``COM_STMT_PREPARE``\n* ``COM_STMT_CLOSE``\n* ``COM_STMT_RESET``",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_questions[$interval]) or irate(mysql_global_status_questions[5m])",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "MySQL TPS",
   "type": "graph",
   "description": "平均每秒事务提交的次数",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_auroradb_commits[$interval]) or irate(mysql_global_status_auroradb_commits[5m])",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "MySQL 慢查询",
   "type": "graph",
   "description": "**MySQL Slow Queries**\n\nSlow queries are defined as queries being slower than the long_query_time setting. For example, if you have long_query_time set to 3, all queries that take longer than 3 seconds to complete will show on this graph.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_slow_queries[$interval]) or irate(mysql_global_status_slow_queries[5m])",
     "legendFormat": "Slow Queries"
    }
   ]
  },
  {
   "title": "MySQL 临时表",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_created_tmp_tables[$interval]) or irate(mysql_global_status_created_tmp_tables[5m])",
     "legendFormat": "Created Tmp Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_created_tmp_disk_tables[$interval]) or irate(mysql_global_status_created_tmp_disk_tables[5m])",
     "legendFormat": "Created Tmp Disk Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_created_tmp_files[$interval]) or irate(mysql_global_status_created_tmp_files[5m])",
     "legendFormat": "Created Tmp Files"
    }
   ]
  },
  {
   "title": "Transaction Trx Rseg History Len",
   "type": "graph",
   "description": "Length of the TRX_RSEG_HISTORY list\n当写库并发执行大查询的时候，transaction history就会因为undo log无法purge而一直增加。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_info_schema_innodb_metrics_transaction_trx_rseg_history_len",
     "legendFormat": "TRX_RSEG_HISTORY"
    }
   ]
  },
  {
   "title": "Adaptive Hash Searches",
   "type": "graph",
   "description": "Number of searches using B-tree on an index search\nNumber of successful searches using Adaptive Hash Index",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_btree_total[$interval]) or rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_btree_total[5m])",
     "legendFormat": "使用 Btree 查询的次数"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total [$interval]) or rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total [5m])",
     "legendFormat": "使用 AHI 方式查询的次数"
    }
   ]
  },
  {
   "title": "MySQL 网络流量",
   "type": "graph",
   "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_received[$interval]) or irate(mysql_global_status_bytes_received[5m])",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_sent[$interval]) or irate(mysql_global_status_bytes_sent[5m])",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "MySQL 网络流量 （按小时统计）",
   "type": "graph",
   "description": "**MySQL Network Usage Hourly**\n\nHere we can see how much network traffic is generated by MySQL per hour. You can use the bar graph to compare data sent by MySQL and data received by MySQL.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_bytes_received[1h])",
     "legendFormat": "Received"
    },
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_bytes_sent[1h])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "MySQL SQL 执行次数",
   "type": "graph",
   "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_global_status_commands_total[$interval])>0) or irate(mysql_global_status_commands_total[5m])>0",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "MySQL SQL 执行次数 （按小时统计）",
   "type": "graph",
   "description": "**Top Command Counters Hourly**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, increase(mysql_global_status_commands_total[1h])>0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "MySQL SQL 影响行数",
   "type": "graph",
   "description": "**innodb_row_ops_total**",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_global_status_innodb_row_ops_total[$interval])>0) or irate(mysql_global_status_innodb_row_ops_total[5m])>0",
     "legendFormat": "Ops_{{ operation }}"
    }
   ]
  },
  {
   "title": "MySQL SQL 影响行数（按小时统计）",
   "type": "graph",
   "description": "\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, increase(mysql_global_status_innodb_row_ops_total[1h])>0)",
     "legendFormat": "Com_{{ operation }}"
    }
   ]
  },
  {
   "title": "MySQL 查询分析",
   "type": "graph",
   "description": "**MySQL Select Types**\n\nAs with most relational databases, selecting based on indexes is more efficient than scanning an entire table's data. Here we see the counters for selects not done with indexes.\n\n* ***Select Scan*** is how many queries caused full table scans, in which all the data in the table had to be read and either discarded or returned.\n* ***Select Range*** is how many queries used a range scan, which means MySQL scanned all rows in a given range.\n* ***Select Full Join*** is the number of joins that are not joined on an index, this is usually a huge performance hit.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_full_join[$interval]) or irate(mysql_global_status_select_full_join[5m])",
     "legendFormat": "Select Full Join"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_full_range_join[$interval]) or irate(mysql_global_status_select_full_range_join[5m])",
     "legendFormat": "Select Full Range Join"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_range[$interval]) or irate(mysql_global_status_select_range[5m])",
     "legendFormat": "Select Range"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_range_check[$interval]) or irate(mysql_global_status_select_range_check[5m])",
     "legendFormat": "Select Range Check"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_scan[$interval]) or irate(mysql_global_status_select_scan[5m])",
     "legendFormat": "Select Scan"
    }
   ]
  },
  {
   "title": "MySQL 排序分析",
   "type": "graph",
   "description": "**MySQL Sorts**\n\nDue to a query's structure, order, or other requirements, MySQL sorts the rows before returning them. For example, if a table is ordered 1 to 10 but you want the results reversed, MySQL then has to sort the rows to return 10 to 1.\n\nThis graph also shows when sorts had to scan a whole table or a given range of a table in order to return the results and which could not have been sorted via an index.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_rows[$interval]) or irate(mysql_global_status_sort_rows[5m])",
     "legendFormat": "Sort Rows"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_range[$interval]) or irate(mysql_global_status_sort_range[5m])",
     "legendFormat": "Sort Range"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_merge_passes[$interval]) or irate(mysql_global_status_sort_merge_passes[5m])",
     "legendFormat": "Sort Merge Passes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_scan[$interval]) or irate(mysql_global_status_sort_scan[5m])",
     "legendFormat": "Sort Scan"
    }
   ]
  },
  {
   "title": "MySQL Handlers",
   "type": "graph",
   "description": "**MySQL Handlers**\n\nHandler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\n\nThis is in fact the layer between the Storage Engine and MySQL.\n\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_handlers_total{container_name=~\"$rds\", handler!~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{container_name=~\"$rds\", handler!~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL Transaction Handlers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_handlers_total{container_name=~\"$rds\", handler=~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{container_name=~\"$rds\", handler=~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL Table Locks",
   "type": "graph",
   "description": "**Table Locks**\n\nMySQL takes a number of different locks for varying reasons. In this graph we see how many Table level locks MySQL has requested from the storage engine. In the case of InnoDB, many times the locks could actually be row locks as it only takes table level locks in a few specific cases.\n\nIt is most useful to compare Locks Immediate and Locks Waited. If Locks waited is rising, it means you have lock contention. Otherwise, Locks Immediate rising and falling is normal activity.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_table_locks_immediate[$interval]) or irate(mysql_global_status_table_locks_immediate[5m])",
     "legendFormat": "Table Locks Immediate"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_table_locks_waited[$interval]) or irate(mysql_global_status_table_locks_waited[5m])",
     "legendFormat": "Table Locks Waited"
    }
   ]
  },
  { "title": "1.5 Files and Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 } },
  {
   "title": "MySQL File Openings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_opened_files[$interval]) or irate(mysql_global_status_opened_files[5m])",
     "legendFormat": "Openings"
    }
   ]
  },
  {
   "title": "MySQL Open Files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "calculatedInterval": "2m", "expr": "mysql_global_status_open_files", "legendFormat": "Open Files" },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_open_files_limit",
     "legendFormat": "Open Files Limit"
    },
    {
     "expr": "mysql_global_status_innodb_num_open_files",
     "legendFormat": "InnoDB Open Files"
    }
   ]
  },
  {
   "title": "MySQL Table Open Cache Status",
   "type": "graph",
   "description": "**MySQL Table Open Cache Status**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_opened_tables[$interval]) or irate(mysql_global_status_opened_tables[5m])",
     "legendFormat": "Openings"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_hits[$interval]) or irate(mysql_global_status_table_open_cache_hits[5m])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_misses[$interval]) or irate(mysql_global_status_table_open_cache_misses[5m])",
     "legendFormat": "Misses"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_overflows[$interval]) or irate(mysql_global_status_table_open_cache_overflows[5m])",
     "legendFormat": "Misses due to Overflows"
    },
    {
     "expr": "(rate(mysql_global_status_table_open_cache_hits[$interval]) or irate(mysql_global_status_table_open_cache_hits[5m]))/((rate(mysql_global_status_table_open_cache_hits[$interval]) or irate(mysql_global_status_table_open_cache_hits[5m]))+(rate(mysql_global_status_table_open_cache_misses[$interval]) or irate(mysql_global_status_table_open_cache_misses[5m])))",
     "legendFormat": "Table Open Cache Hit Ratio"
    }
   ]
  },
  {
   "title": "MySQL Open Tables",
   "type": "graph",
   "description": "**MySQL Open Tables**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_tables",
     "legendFormat": "Open Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_open_cache",
     "legendFormat": "Table Open Cache"
    }
   ]
  }
 ]
}